/* ==========================================
   歌词数据库 (lyrics.js)
   这里专门录入每首歌对应的单行时间戳歌词
   ========================================== */
const lyricsDatabase = {
  // 对应歌曲 ID: 渭水钓翁的歌词 (必须与 songs.js 里的 lyricId 完全一致)
  "song_1790441880313": [
    { time: 0, text: "作词 : （唐）胡曾/辛晓娟" },
    { time: 0, text: "作曲 : 王铮亮" },
    { time: 1, text: "演唱 : 王铮亮/王珮瑜" },
    { time: 1, text: "制作人：刘卓" },
    { time: 1, text: "编曲：柒玖" },
    { time: 1, text: "混音：黄可爱@维伴音乐" },
    { time: 2, text: "音频编辑：石行@维伴音乐" },
    { time: 2, text: "混音：张伊然@维伴音乐" },
    { time: 9, text: "王珮瑜：" },
    { time: 23, text: "岸草青青渭水流" },
    { time: 27, text: "子牙曾此独垂钩" },
    { time: 32, text: "风云一遇碧霄上" },
    { time: 36, text: "不向斜阳叹白头" },
    { time: 41, text: "王铮亮：" },
    { time: 49, text: "亘古奔流 渭水汤汤" },
    { time: 53, text: "谁悬钩三尺" },
    { time: 55, text: "垂钓风波之上" },
    { time: 58, text: "飞熊入梦 说钓者姓姜名尚" },
    { time: 67, text: "王珮瑜：" },
    { time: 67, text: "下昆仑 入凡尘" },
    { time: 70, text: "只为那河山生光" },
    { time: 76, text: "王铮亮：" },
    { time: 77, text: "人不识 又何如" },
    { time: 80, text: "且屠沽浪迹四方" },
    { time: 86, text: "如今坐钓台" },
    { time: 88, text: "一袖风 一蓑雪" },
    { time: 90, text: "等一场云从龙翔" },
    { time: 95, text: "如今抬钓竿" },
    { time: 97, text: "一尺升 一寸降" },
    { time: 100, text: "将天下苍生称量" },
    { time: 104, text: "王珮瑜：" },
    { time: 105, text: "昔年我游九州" },
    { time: 107, text: "肩上日 枕上月" },
    { time: 109, text: "脚下尺丈量洪荒" },
    { time: 114, text: "如今我坐钓台" },
    { time: 116, text: "空中钩 掌中线" },
    { time: 118, text: "合：" },
    { time: 119, text: "稳系住四海沧浪" },
    { time: 126, text: "王珮瑜：" },
    { time: 128, text: "周文王飞熊梦见" },
    { time: 133, text: "散宜生奏访遗贤" },
    { time: 138, text: "姜子牙鹤发伴童颜" },
    { time: 142, text: "打柴汉武吉引见" },
    { time: 148, text: "车辇行来 八百单八步" },
    { time: 155, text: "河山平安 八百单八年" },
    { time: 162, text: "合：" },
    { time: 163, text: "如今坐钓台" },
    { time: 166, text: "一袖风 一蓑雪" },
    { time: 168, text: "等一场云从龙翔（等一场云从龙翔）" },
    { time: 173, text: "如今抬钓竿" },
    { time: 175, text: "一尺升 一寸降" },
    { time: 177, text: "将天下苍生称量" },
    { time: 182, text: "昔年我游九州" },
    { time: 184, text: "肩上日 枕上月" },
    { time: 187, text: "脚下尺丈量洪荒" },
    { time: 191, text: "如今我坐钓台" },
    { time: 194, text: "空中钩 掌中线" },
    { time: 196, text: "稳系住四海沧浪" },
    { time: 204, text: "王铮亮：" },
    { time: 207, text: "岸草青青渭水流" },
    { time: 210, text: "子牙曾此独垂钩" },
    { time: 215, text: "王珮瑜：" },
    { time: 216, text: "当时未入非熊兆" },
    { time: 220, text: "合：" },
    { time: 220, text: "几向斜阳叹白头" }
  ],
  "song_1790484169186": [
    { time: 0, text: "作词 : 林夕" },
    { time: 1, text: "作曲 : Choi Sung Wook" },
    { time: 5, text: "编曲：邢迟" },
    { time: 35, text: "你微笑 不代表你想拥抱" },
    { time: 42, text: "你的拥抱 不代表一切美好" },
    { time: 49, text: "如果说 梦想是一个气泡" },
    { time: 56, text: "至少我能够 触摸得到" },
    { time: 70, text: "我眼睛 看不见你的需要" },
    { time: 78, text: "你的耳朵 听不到我的祈祷" },
    { time: 85, text: "如果说 天气都难以预告" },
    { time: 92, text: "爱情的痕迹 往哪里找" },
    { time: 98, text: "我要对你多好 你要爱我多少" },
    { time: 106, text: "有什么重要 也许答案得" },
    { time: 112, text: "走过天涯海角 最后才知道" },
    { time: 123, text: "听得见你心在跳 最重要" },
    { time: 164, text: "你的泪 不代表我的烦恼" },
    { time: 171, text: "我的感动 不代表你的心跳" },
    { time: 178, text: "也难怪 亲吻的时候须要" },
    { time: 185, text: "闭起了眼睛 才有味道" },
    { time: 191, text: "我要对你多好 你要爱我多少" },
    { time: 199, text: "有什么重要 也许答案得" },
    { time: 206, text: "走过天涯海角 最后才知道" },
    { time: 217, text: "听得见你心在跳 最重要" },
    { time: 229, text: "我要对你多好 你要爱我多少" },
    { time: 237, text: "有什么重要 也许答案得" },
    { time: 243, text: "走过天涯海角 最后才知道" },
    { time: 258, text: "听得见你心在跳 最重要" }
  ],
 
